### ISSUE TITLE
About usage

### ISSUE THREAD

**Issue by zauster** [tecosaur/DaemonConductor.jl#1]
Hey,

I read through the README but some questions have come up:

1. Where I have repeatedly used `julia run_my_simulation.jl --someflag` I could now use `juliaclient run_my_simulation.jl --someflag` and the computations in the `.jl` file would be passed to a worker process running in the background?
2. This worker process is started at the first invocation and then kept running until 2h after the last computation?
3. Could there be multiple worker process (you mention one worker process 'per project'), such that the first call to `juliaclient` is executed on worker process 1, the next call on worker process 2 (since the process on 1 is still running) and so on?
4. Would it then also be possible to start the worker process on a separate machine and offload the computation to there? 

My use case: I have a large number of simulations that I want to run. The simulation is programmed in Julia. Each simulation run is started with different parameters. These parameters are determined by an algorithm programmed in Python and not known beforehand.

**Comment by tecosaur** [comment]
Happy to answer your queries.

1. Yes
2. Yes
3. Not yet, but I've been thinking of making a change which will allow for this
4. Almost, you'd just need to use the network connection instead of the socket. A PR to make the workers work over a network instead of via a socket would be needed.

**Comment by tecosaur** [comment]
Update: I've now done (3), but you'll want to wait till I get around to releasing v0.3

**Comment by zauster** [comment]
Awesome, thanks a lot!
