### ISSUE TITLE
Default socket not found

### ISSUE THREAD

**Issue by zauster** [tecosaur/DaemonConductor.jl#2]
Hey,

I git cloned your repo, followed the installation steps and then called `juliaclient`:

```
% juliaclient
Socket file /run/user/1000/julia-daemon.sock does not exist.
Are you sure the daemon is running?

% ls -l /run/user/1000/julia-daemon
insgesamt 0
srwxr-xr-x  1 reitero reitero   0 16. Jun 13:23 conductor.sock
```

It does work when I explicitly set `export JULIA_DAEMON_SERVER=/run/user/1000/julia-daemon/conductor.sock`.

**Comment by tecosaur** [comment]
Hmm, that sounds like an issue with the client. I think it should work though with the envvar?

https://github.com/tecosaur/DaemonConductor.jl/blob/1ddd5839960f80296b297f789ab682981f1a2abd/client/client.zig#L70-L81

**Comment by zauster** [comment]
Yes, it does work when JULIA_DAEMON_SERVER is set. If it is unset, it does not work.

**Comment by zauster** [comment]
Seems the server (or worker) and the client have different default sockets?

**Comment by tecosaur** [comment]
Right, so this is just a case of the default changing post-0.2, but you've got the 0.2 client.

This will be resolved in 0.3.

**Comment by zauster** [comment]
But since I cloned your repo, I have the development version. Is this not the 0.3 version?

**Comment by tecosaur** [comment]
0.3 will be out soon. You can get the 0.3 client for now by compiling `client.zig` yourself.

**Comment by zauster** [comment]
Ah, I understand. Thanks for explaining!
