### ISSUE TITLE
Command line args not passed to script

### ISSUE THREAD

**Issue by zauster** [tecosaur/DaemonConductor.jl#4]
Hey, 

another find. I have a file `test.jl`:

```{julia}
cd(@__DIR__)
cur_dir = pwd()
using Pkg
Pkg.activate(cur_dir)
using ArgParse

function parse_commandline()
    s = ArgParseSettings()

    ## if the flag is used, the value is set to true
    @add_arg_table s begin
        "--some_flag"
        help = "Some flag"
        action = :store_true
    end
    return parse_args(s)
end

function main()
    parsed_args = parse_commandline()
    println(parsed_args)
end

main()
```

1. This does however not yield the intended behaviour when using with `juliaclient`. The value is still 'false' when the flag is included:
```
% julia test.jl
  Activating project at `~/test`
Dict{String, Any}("some_flag" => false)

% julia test.jl --some_flag
  Activating project at `~/test`
Dict{String, Any}("some_flag" => true)

% juliaclient test.jl
  Activating project at `~/test`
Dict{String, Any}("some_flag" => false)

% juliaclient test.jl --some_flag
  Activating project at `~/test`
Dict{String, Any}("some_flag" => false)
```
I have also tried `juliaclient -- test.jl --some_flag` (as in the help docstring) with the same result.

Furthermore, the docstring is not printed when `--help` is given, the script is just run again:
```
% julia test.jl --help
  Activating project at `~/test`
usage: test.jl [--some_flag] [-h]

optional arguments:
  --some_flag  Some flag
  -h, --help   show this help message and exit

% juliaclient test.jl --help
  Activating project at `~/test`
Dict{String, Any}("some_flag" => false)
```

2. Additionally, with `-L` it loads the file and starts a REPL, is this intended?

```
└──╼ % juliaclient -L test.jl
  Activating project at `~/test`
Dict{String, Any}("some_flag" => false)
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.1 (2023-06-07)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> exit()
```

3. Just a minor thing: after typing `exit()`, I have to press enter twice to return to the terminal.

To make sure that this is not again a client 0.2/0.3 thing, I compiled the `client.zig` with the command given in the file and moved the binary to the corresponding folder. `juliaclient` started right away (without needing to set the var JULIA_DAEMON_SERVER) which seems to indicate that this is the 0.3 client.

**Comment by tecosaur** [comment]
Hmmm, interesting, I can't reproduce this on my machine, but I am trying a simpler example.

```sh
~$ 'println(ARGS)' > /tmp/test.jl
~$ juliaclient /tmp/test.jl -arg value --flag
["-arg", "value", "--flag"]
```

**Comment by zauster** [comment]
Ah, that indeed interesting. 

I found the faulty line, in the [ArgParse docs](https://argparsejl.readthedocs.io/en/latest/argparse.html) they have this example:

```
function parse_commandline()
    s = ArgParseSettings()
    ## some code
    return parse_args(s) ## <<-- line of interest
end
```
with the following change it does work then also with `juliaclient`:
```
function parse_commandline()
    s = ArgParseSettings()
    ## some code
    return parse_args(ARGS, s) ## include ARGS
end
```

Now the flag with `--some_flag` is correctly set to true:
```
% juliaclient test.jl --some_flag        
  Activating project at `~/test`
Dict{String, Any}("arg" => 1, "some_flag" => true)
```

Conclusio: with `juliaclient` and `ArgParse` it seems one has to explicitly tell `ArgParse` to parse the `ARGS` ;-)

Thanks for your prompt response (again)!

**Comment by tecosaur** [comment]
Interesting. I am aiming for as close to 100% compatibility with `julia` as possible, so it would be good to know where `ArgParse`'s defaults come from...
