### ISSUE TITLE
Previously sourced function 'not defined'

### ISSUE THREAD

**Issue by zauster** [tecosaur/DaemonConductor.jl#5]
Good evening!

When I try to do the following:
- source a file (`setup.jl`) with a function definition with `juliaclient`
- call that function in another script (`run.jl`) again with `juliaclient`, it tells me that this function is 'not defined'.

However, since the background worker process is always running (and it is the same worker, I let it print its PID), I was expecting the function to still be defined when I call it at a later point in time.

Reprex:

```{sh}
julia -e 'using Pkg; Pkg.generate("test")'
cd test
echo "
println(getpid())
function simulate()
    x = Float64[]
    for i in 1:100
        push!(x, rand())
    end
    return x
end
res = simulate()
println(res)" > src/setup.jl
echo "
println(getpid())
simulate()" > src/run.jl
juliaclient --project=. src/setup.jl   ## output is displayed
juliaclient --project=. src/run.jl     ## ERROR: LoadError: UndefVarError: `simulate` not defined
```

Do you know what's the issue or can you explain what I am misunderstanding? Is maybe the function loaded in some submodule and not available from Main?

Thanks for your help in advance!

**Comment by tecosaur** [comment]
Each time a script is run, it's done in a temporary module/namespace.

The whole idea here is that `juliaclient` is a drop-in for `julia` with lower latency. You wouldn't expect this to work:

```sh
~$ julia -E "a=1"
1

~$ julia -E "a"
1
```

**Comment by zauster** [comment]
I see your point, but at the same time I am a bit confused.

How do you achieve then the lower latency if functions need to be re-compiled, modules be re-imported at every start of juliaclient? And how can one "run a script many times, compile it once" as it says in the README?
Could you briefly explain how _you_ use DaemonConductor? Maybe that makes it clearer

**Comment by zauster** [comment]
Could you point me to the function/section where I could disable these temporary module/namespaces (assuming it is possible to do this)?

**Comment by tecosaur** [comment]
There's no setting to disable this. Anyway, here's an example of that reduced latncy I'm talking about:

```julia
~$ hyperfine 'julia --startup-file=no -E "using DataFrames; DataFrame(a = [1, 2]).a |> sum"'
Benchmark #1: julia --startup-file=no -E "using DataFrames; DataFrame(a = [1, 2]).a |> sum"
  Time (mean ± σ):     652.5 ms ±  15.4 ms    [User: 767.5 ms, System: 582.0 ms]
  Range (min … max):   630.4 ms … 677.1 ms    10 runs

~$ hyperfine 'juliaclient -E "using DataFrames; DataFrame(a = [1, 2]).a |> sum"'
Benchmark #1: juliaclient --startup-file=no -E "using DataFrames; DataFrame(a = [1, 2]).a |> sum"
  Time (mean ± σ):       6.1 ms ±   3.4 ms    [User: 1.4 ms, System: 1.3 ms]
  Range (min … max):     5.2 ms …  49.2 ms    475 runs
```

**Comment by zauster** [comment]
Ah, quite a difference...

Sorry, I was unclear: I meant if you point me to where I could implement this myself (assuming this is possible)?
