### ISSUE TITLE
Same worker process is used for different projects

### ISSUE THREAD

**Issue by zauster** [tecosaur/DaemonConductor.jl#6]
Hello, 

me again. `juliaclient` should spawn a different worker process for different projects, correct? However, I see the same PID when I call `juliaclient` in different projects.

Reprex:

```{sh}
## create first project
julia -e 'using Pkg; Pkg.generate("test_XXX")'
echo "println(getpid())" > test_XXX/src/run.jl
## create second project
julia -e 'using Pkg; Pkg.generate("test_YYY")'
echo "println(getpid())" > test_YYY/src/run.jl
## run juliaclient in first project
cd test_XXX
juliaclient --project=. src/run.jl ## PID 1234 (e.g.)
## run juliaclient in second project
cd ../test_YYY
juliaclient --project=. src/run.jl ## again PID 1234
```

I would have expected to see different PIDs. A second worker process with a different PID _is_ started, but remains idle.

The process with that PID is started like this:

```
% ps aux | grep '1234'
reitero     1234  0.4  2.0 1707480 315668 ?      Sl   09:27   0:04 /usr/bin/julia --project=/home/reitero/.cache/julia-daemon-0-2-0-worker-env --startup-file=no --eval using DaemonWorker; DaemonWorker.runworker("/run/user/1000/julia-daemon/wsetup-gokqdg.sock")
```

**Comment by tecosaur** [comment]
I've just done a little testing myself. There's something to look into here, I'll get to it in a bit.

```sh
~$ juliaclient -E "getpid()"
2780
~$ juliaclient -E "getpid()" --project=/tmp
2780
~$ juliaclient -E "getpid()" --project=~/.julia/dev/BaseDirs
2780
~$ juliaclient -E "getpid()" --project=/home/tec/.julia/dev/BaseDirs
2780
~$ juliaclient --project=/home/tec/.julia/dev/BaseDirs -E "getpid()"
29745
~$ juliaclient --project=. -E "getpid()"
29876
~$ juliaclient --project=/tmp -E "getpid()"
29941
~$ juliaclient --project=. -E "getpid()"
29876
~$ /tmp
~$ juliaclient --project=. -E "getpid()"
29976
~$ ~/.julia/dev/BaseDirs/
~$ juliaclient --project=. -E "getpid()"
30240
~$ ~
~$ juliaclient --project=. -E "getpid()"
29876
```

**Comment by zauster** [comment]
Could it be at 'project' here
https://github.com/tecosaur/DaemonConductor.jl/blob/4e4d50fe1d5e88b7fe7dbcfd2ff823c36a6a6484/src/workers.jl#L67

is always `nothing`?

I have added a string to identify the project for which a worker is started:
https://github.com/tecosaur/DaemonConductor.jl/compare/master...zauster:DaemonConductor.jl:add_project_string

All worker process have empty project strings.

**Comment by tecosaur** [comment]
A worker initially being created with no project is fine, it is assigned a project later. If you actually want to test this, the way is:

```sh
~$ juliaclient -E "using Pkg; Pkg.project().path"
"/home/tec/.julia/environments/v1.9/Project.toml"

~$ ~/.julia/dev/BaseDirs

~$ juliaclient -E "using Pkg; Pkg.project().path"
"/home/tec/.julia/dev/BaseDirs/Project.toml"
```

**Comment by zauster** [comment]
Hey, thanks. Works as expected with the recent commit!
